openapi: 3.0.0
info:
  title: Order API
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/products/{id}':
    parameters:
      - schema:
          type: number
        name: id
        in: path
        required: true
    get:
      summary: Fetch product details
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './common.yaml#/components/schemas/Product'
      operationId: get-product-id
    post:
      summary: Update product details
      operationId: post-products-id
      responses:
        '204':
          description: No Content
      requestBody:
        content:
          application/json:
            schema:
              $ref: './common.yaml#/components/schemas/Product'
      parameters:
        - schema:
            type: string
          in: header
          name: Authenticate
          required: true
    delete:
      summary: Delete a product
      operationId: delete-products-id
      responses:
        '204':
          description: No Content
      parameters:
        - schema:
            type: string
          in: header
          name: Authenticate
          required: true
  /products:
    post:
      summary: Add new product
      operationId: post-products
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: './common.yaml#/components/schemas/ProductId'
      parameters:
        - schema:
            type: string
          in: header
          name: Authenticate
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: './common.yaml#/components/schemas/ProductDetails'
    get:
      summary: Search for products
      operationId: get-products
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './common.yaml#/components/schemas/Product'
        '500':
          description: OK
          content:
            application/json:
              schema:
                type: string
      parameters:
        - schema:
            type: string
          in: query
          name: name
        - schema:
            type: string
          in: query
          name: type
  /orders:
    post:
      summary: Create an order
      operationId: post-orders
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: './common.yaml#/components/schemas/OrderId'
      parameters:
        - schema:
            type: string
          in: header
          name: Authenticate
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: './common.yaml#/components/schemas/OrderDetails'
    get:
      summary: Search for orders
      operationId: get-orders
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './common.yaml#/components/schemas/Order'
      parameters:
        - schema:
            type: number
          in: query
          name: productid
        - schema:
            type: string
          in: query
          name: status
      description: ''
  '/orders/{id}':
    parameters:
      - schema:
          type: number
        name: id
        in: path
        required: true
    get:
      summary: Fetch order details
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './common.yaml#/components/schemas/Order'
      operationId: get-orders-id
      parameters: []
    post:
      summary: Update order details
      operationId: post-orders-id
      responses:
        '204':
          description: No Content
      parameters:
        - schema:
            type: string
          in: header
          name: Authenticate
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: './common.yaml#/components/schemas/Order'
    delete:
      summary: Cancel an order
      operationId: delete-orders-id
      responses:
        '204':
          description: No Content
      parameters:
        - schema:
            type: string
          in: header
          name: Authenticate
          required: true