name: Specmatic Insights Central Contract Repo Report

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "17"

      - name: Setup Specmatic
        uses: airslate-oss/setup-specmatic@v1
        with:
          specmatic-version: 1.3.18

      - name: Generate central contract repo report
        run: specmatic central-contract-repo-report

      - name: Install Specmatic Insights Github Build Reporter
        run: npm install -g specmatic-insights-github-build-reporter

      - name: Run Specmatic Insights Github Build Reporter
        working-directory: .
        run: npx specmatic-insights-github-build-reporter --specmatic-insights-host https://insights.specmatic.in --specmatic-central-repo-report ./build/reports/specmatic/central_contract_repo_report.json
        env:
          SPECMATIC_ORG_ID: ${{ secrets.SPECMATIC_ORG_ID }}
          GITHUB_TOKEN: ${{ secrets.SPECMATIC_INSIGHTS_ACCESS_TOKEN }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
