name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  get-changed-yaml-files:
    runs-on: ubuntu-latest
    name: Get changed yaml files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - uses: tj-actions/changed-files@v34
        id: changed-files-specific
        with:
          files: |
            io/**/*.yaml
            io/**/*.yml
            io/**/*.json
          files_ignore: kafka.yaml #skipping it as async is under private-beta

  get-changed-graphqls-files:
    runs-on: ubuntu-latest
    name: Get changed GraphQLS files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - uses: tj-actions/changed-files@v34
        id: changed-graphqls-files
        with:
          files: |
            io/**/*.graphqls

  install-spectral-linter:
    runs-on: ubuntu-latest
    name: Install Spectral Linter
    needs: get-changed-yaml-files
    if: steps.changed-files-specific.outputs.any_changed == 'true'
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '20'

      - run: npm install -g @stoplight/spectral-cli

  run-spectral-linter:
    runs-on: ubuntu-latest
    name: Run Spectral linter on changed files
    needs: install-spectral-linter
    if: steps.changed-files-specific.outputs.any_changed == 'true'
    steps:
      - run: |
          echo "Running Spectral linter on: ${{ steps.changed-files-specific.outputs.all_changed_files }}"
          spectral lint io/**/*.yaml

  validate-graphql-examples:
    runs-on: ubuntu-latest
    name: Validate GraphQL examples
    needs: get-changed-graphqls-files
    if: steps.changed-graphqls-files.outputs.any_changed == 'true'
    steps:
      - run: |
          docker run -v "$(pwd):/central-contract-repo:rw" \
            --entrypoint /bin/sh \
            znsio/specmatic-graphql-trial \
            -c "cd /central-contract-repo && java -jar /usr/src/app/specmatic-graphql.jar examples validate --spec-file io/specmatic/examples/store/graphql/products_bff.graphqls"

  create-environment-file:
    runs-on: ubuntu-latest
    name: Create environment file
    steps:
      - run: |
            echo "GITHUB_SHA=${{ github.sha }}" >> env.list
            echo "GITHUB_REPOSITORY=${{ github.repository }}" >> env.list
            echo "GITHUB_ACTOR=${{ github.actor }}" >> env.list
            echo "GITHUB_WORKFLOW=${{ github.workflow }}" >> env.list
            echo "GITHUB_HEAD_REF=${{ github.head_ref }}" >> env.list
            if [ -z "${{ github.base_ref }}" ]; then
                echo "GITHUB_BASE_REF=${{ github.ref }}" | sed 's/refs\/heads\///' >> env.list
            else
              echo "GITHUB_BASE_REF=${{ github.base_ref }}" >> env.list

  run-openapi-backward-compatibility-check:
    runs-on: ubuntu-latest
    name: Run OpenAPI backward compatibility check on changed files
    needs: get-changed-yaml-files
    if: steps.changed-files-specific.outputs.any_changed == 'true'
    steps:
      - run: |
          docker run -v "$(pwd):/central-contract-repo:rw" \
            --env-file env.list \
            --entrypoint /bin/sh znsio/specmatic \
            -c "git config --global --add safe.directory /central-contract-repo && cd /central-contract-repo && java -jar /usr/src/app/specmatic.jar backward-compatibility-check --base-branch origin/main"

  run-graphql-backward-compatibility-check:
    runs-on: ubuntu-latest
    name: Run GraphQL backward compatibility check on changed files
    needs: get-changed-graphqls-files
    if: steps.changed-graphqls-files.outputs.any_changed == 'true'
    steps:
      - run: |
          docker run -v "$(pwd):/central-contract-repo:rw" \
            --env-file env.list \
            --entrypoint /bin/sh \
            znsio/specmatic-graphql-trial \
            -c "git config --global --add safe.directory /central-contract-repo && cd /central-contract-repo && java -jar /usr/src/app/specmatic-graphql.jar backward-compatibility-check --base-branch origin/main"
