name: CI
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      yaml_changed: '${{ steps.changed-files-yaml.outputs.any_changed }}'
      graphql_changed: '${{ steps.changed-graphqls-files.outputs.any_changed }}'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: tj-actions/changed-files@v34
        id: changed-files-yaml
        with:
          files: |
            io/**/*.yaml
            io/**/*.yml
            io/**/*.json
          files_ignore: kafka.yaml
      - uses: tj-actions/changed-files@v34
        id: changed-graphqls-files
        with:
          files: |
            io/**/*.graphqls
  specmatic-yaml-validation:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: '${{ needs.detect-changes.outputs.yaml_changed == ''true'' }}'
    name: YAML Validation
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Spectral Linter for YAML
        run: npm install -g @stoplight/spectral-cli
      - name: Run Spectral Linter on YAML files
        run: spectral lint io/**/*.yaml
      - name: Run OpenAPI examples validation check
        run: >
          docker run -v "$(pwd):/central-contract-repo:rw" znsio/specmatic
          examples validate \
            --contract-file /central-contract-repo/io/specmatic/examples/store/openapi/product_search_bff_v4.yaml
      - name: Create environment file
        run: |
          # echo "GITHUB_REF=${{ github.ref }}" >> env.list
          echo "GITHUB_SHA=${{ github.sha }}" >> env.list
          echo "GITHUB_REPOSITORY=${{ github.repository }}" >> env.list
          echo "GITHUB_ACTOR=${{ github.actor }}" >> env.list
          echo "GITHUB_WORKFLOW=${{ github.workflow }}" >> env.list
          echo "GITHUB_HEAD_REF=${{ github.head_ref }}" >> env.list
          if [ -z "${{ github.base_ref }}" ]; then
              echo "GITHUB_BASE_REF=${{ github.ref }}" | sed 's/refs\/heads\///' >> env.list
          else
            echo "GITHUB_BASE_REF=${{ github.base_ref }}" >> env.list
          fi   
      - name: Run OpenAPI backward compatibility check
        run: |
          docker run -v "$(pwd):/central-contract-repo:rw" \
            --env-file env.list \
            --entrypoint /bin/sh znsio/specmatic \
            -c "git config --global --add safe.directory /central-contract-repo && cd /central-contract-repo && java -jar /usr/src/app/specmatic.jar backward-compatibility-check --base-branch origin/main"
  specmatic-graphql-validation:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: '${{ needs.detect-changes.outputs.graphql_changed == ''true'' }}'
    name: GraphQL Validation
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Spectral Linter for GraphQL
        run: npm install -g @stoplight/spectral-cli
      - name: Run Spectral Linter on GraphQL files
        run: spectral lint io/**/*.graphqls
      - name: Validate GraphQL examples
        run: |
          docker run -v "$(pwd):/central-contract-repo:rw" \
            --entrypoint /bin/sh \
            znsio/specmatic-graphql-trial \
            -c "cd /central-contract-repo && java -jar /usr/src/app/specmatic-graphql.jar examples validate --spec-file io/specmatic/examples/store/graphql/products_bff.graphqls"
      - name: Create environment file
        run: |
          # echo "GITHUB_REF=${{ github.ref }}" >> env.list
          echo "GITHUB_SHA=${{ github.sha }}" >> env.list
          echo "GITHUB_REPOSITORY=${{ github.repository }}" >> env.list
          echo "GITHUB_ACTOR=${{ github.actor }}" >> env.list
          echo "GITHUB_WORKFLOW=${{ github.workflow }}" >> env.list
          echo "GITHUB_HEAD_REF=${{ github.head_ref }}" >> env.list
          if [ -z "${{ github.base_ref }}" ]; then
              echo "GITHUB_BASE_REF=${{ github.ref }}" | sed 's/refs\/heads\///' >> env.list
          else
            echo "GITHUB_BASE_REF=${{ github.base_ref }}" >> env.list
          fi   
      - name: Run GraphQL backward compatibility check
        run: |
          docker run -v "$(pwd):/central-contract-repo:rw" \
            --env-file env.list \
            --entrypoint /bin/sh \
            znsio/specmatic-graphql-trial \
            -c "git config --global --add safe.directory /central-contract-repo && cd /central-contract-repo && java -jar /usr/src/app/specmatic-graphql.jar backward-compatibility-check --base-branch origin/main"
  summary:
    runs-on: ubuntu-latest
    needs:
      - yaml-validation
      - graphql-validation
    steps:
      - name: Summarize Results
        run: >
          echo "YAML Validation Result: ${{ needs.yaml-validation.result }}"

          echo "GraphQL Validation Result: ${{ needs.graphql-validation.result
          }}"
