name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Check API Contracts
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Get changed yaml files
        id: changed-files-specific
        uses: tj-actions/changed-files@v34
        with:
          files: |
            in/**/*.yaml
      
      - name: Install Spectral Linter
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: npm install -g @stoplight/spectral-cli

      - name: Run Spectral linter on changed files
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          echo "Running Spectral linter on: ${{ steps.changed-files-specific.outputs.all_changed_files }}"
          spectral lint in/**/*.yaml

      - name: Run backward compatibility check on changed files
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          echo "Running backward compatibility checks on: ${{ steps.changed-files-specific.outputs.all_changed_files }}"
          chmod +x ./backward_compatibility.sh
          ./backward_compatibility.sh "${{ steps.changed-files-specific.outputs.all_changed_files }}"
